-- Insert sample courses if they don't exist
INSERT INTO public.courses (
  title, 
  description, 
  instructor_name, 
  category, 
  level, 
  duration_hours, 
  price, 
  rating, 
  students_count, 
  lessons_count,
  tags,
  is_published
) VALUES 
  (
    'Python для начинающих',
    'Изучите основы программирования на Python с нуля. Курс включает переменные, циклы, функции и работу с данными.',
    'Алексей Петров',
    'Programming',
    'beginner',
    40,
    15000,
    4.8,
    342,
    25,
    '["Python", "Программирование", "Начинающие"]'::jsonb,
    true
  ),
  (
    'UI/UX дизайн с нуля до профи',
    'Полный курс по UI/UX дизайну. Научитесь создавать красивые и удобные интерфейсы в Figma.',
    'Мария Сидорова',
    'Design',
    'intermediate',
    60,
    25000,
    4.9,
    567,
    40,
    '["UI/UX", "Figma", "Дизайн"]'::jsonb,
    true
  ),
  (
    'React и TypeScript: Продвинутый курс',
    'Глубокое погружение в React 18, TypeScript, Redux Toolkit и современные практики разработки.',
    'Дмитрий Иванов',
    'Programming',
    'advanced',
    80,
    35000,
    4.7,
    234,
    50,
    '["React", "TypeScript", "Frontend"]'::jsonb,
    true
  ),
  (
    'Data Science и Machine Learning',
    'Освойте анализ данных, машинное обучение и нейронные сети на практике с Python.',
    'Анна Козлова',
    'Data Science',
    'intermediate',
    100,
    45000,
    4.9,
    189,
    60,
    '["Python", "ML", "Data Science"]'::jsonb,
    true
  ),
  (
    'iOS разработка на Swift',
    'Создайте свое первое iOS приложение. SwiftUI, работа с API, публикация в App Store.',
    'Игорь Смирнов',
    'Mobile',
    'beginner',
    50,
    28000,
    4.6,
    156,
    30,
    '["Swift", "iOS", "Mobile"]'::jsonb,
    true
  ),
  (
    'Графический дизайн в Adobe Suite',
    'Мастер-класс по Photoshop, Illustrator и InDesign. От основ до профессиональных проектов.',
    'Елена Волкова',
    'Design',
    'beginner',
    45,
    20000,
    4.8,
    423,
    35,
    '["Adobe", "Photoshop", "Illustrator"]'::jsonb,
    true
  )
ON CONFLICT DO NOTHING;

-- Insert sample events if they don't exist
INSERT INTO public.events (
  title,
  description,
  event_type,
  organizer_name,
  location,
  is_online,
  start_date,
  end_date,
  max_participants,
  current_participants,
  price,
  tags,
  is_published
) VALUES
  (
    'Карьера в IT: с чего начать в 2025',
    'Онлайн-вебинар для тех, кто хочет начать карьеру в IT. Обсудим актуальные направления, зарплаты и карьерные траектории.',
    'webinar',
    'NAVYK Team',
    NULL,
    true,
    (NOW() + interval '3 days')::timestamptz,
    (NOW() + interval '3 days' + interval '2 hours')::timestamptz,
    500,
    87,
    0,
    '["Карьера", "IT", "Начинающие"]'::jsonb,
    true
  ),
  (
    'Воркшоп: Создаем Landing Page за 3 часа',
    'Практический воркшоп по созданию продающего лендинга. Разберем структуру, дизайн и конверсию.',
    'workshop',
    'Максим Новиков',
    'Алматы, ул. Достык 123',
    false,
    (NOW() + interval '5 days')::timestamptz,
    (NOW() + interval '5 days' + interval '3 hours')::timestamptz,
    30,
    12,
    5000,
    '["Web", "Дизайн", "Практика"]'::jsonb,
    true
  ),
  (
    'AI Митап Алматы: Новости и тренды',
    'Встреча сообщества AI-разработчиков. Доклады про GPT-4, ML модели и практическое применение.',
    'meetup',
    'AI Community',
    'Алматы, Tech Hub',
    false,
    (NOW() + interval '7 days')::timestamptz,
    (NOW() + interval '7 days' + interval '4 hours')::timestamptz,
    80,
    45,
    0,
    '["AI", "ML", "Сообщество"]'::jsonb,
    true
  ),
  (
    'DevFest Kazakhstan 2025',
    'Крупнейшая IT-конференция Казахстана. 20+ спикеров, мастер-классы, нетворкинг.',
    'conference',
    'GDG Kazakhstan',
    'Астана, Expo Center',
    false,
    (NOW() + interval '14 days')::timestamptz,
    (NOW() + interval '14 days' + interval '8 hours')::timestamptz,
    500,
    234,
    10000,
    '["Конференция", "Dev", "Нетворкинг"]'::jsonb,
    true
  ),
  (
    'Хакатон: FinTech Solutions',
    '48-часовой хакатон по созданию финтех-решений. Призовой фонд 500,000₸!',
    'hackathon',
    'Kaspi Tech',
    'Алматы, Kaspi Lab',
    false,
    (NOW() + interval '21 days')::timestamptz,
    (NOW() + interval '23 days')::timestamptz,
    100,
    67,
    2000,
    '["Хакатон", "FinTech", "Coding"]'::jsonb,
    true
  ),
  (
    'UX Research: Методы и практика',
    'Онлайн-вебинар о современных методах UX-исследований. Интервью, тестирование, аналитика.',
    'webinar',
    'Айгуль Жунусова',
    NULL,
    true,
    (NOW() + interval '10 days')::timestamptz,
    (NOW() + interval '10 days' + interval '90 minutes')::timestamptz,
    300,
    156,
    0,
    '["UX", "Research", "Дизайн"]'::jsonb,
    true
  )
ON CONFLICT DO NOTHING;